config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get "up" => "rails/health#show", as: :rails_health_check
  resources :events, only: [:index, :create]
  root to: "events#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_events
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  self.inheritance_column = nil
  enum type: [:event_a, :event_b]

  after_create :create_iterable_event

  private

  def create_iterable_event
    CreateEventsJob.perform_later(user.id, self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = current_user&.user_events
  end

  def create
    respond_to do |format|
      current_user.user_events.create!(name: "#{params[:type].camelcase}", type: params[:type])
      format.html { redirect_to root_path, notice: 'Event created successfully.' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<% if user_signed_in? %>
  <h1>Welcome Home, <%= current_user.email %></h1>
  <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
  
  <div>
    <div>
      <%= button_to "Create Event A", events_path(type: 'event_a'), method: :post %>
      <%= button_to "Create Event B", events_path(type: 'event_b'), method: :post %>
    </div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Event Type</th>
          <th>Event Created At</th>
          <th>Email Delivered At</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.id %></td>
            <td><%= event.name %></td>
            <td><%= event.user&.email %></td>
            <td><%= event.type %></td>
            <td><%= event.event_created_at %></td>
            <td><%= event.email_delivered_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <h1>Home</h1>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>